-- =====================================================================
--  Rollback for 20260910_0004_analytics_views.sql
--
--  Views hold no data, so this is safe to run and re-apply. dim_date is
--  dropped too; it is regenerated by the up migration.
-- =====================================================================

drop function if exists public.refresh_dashboard();
drop materialized view if exists public.mv_dashboard_summary;

drop view if exists public.v_overdue_actions;
drop view if exists public.v_survey_diary;
drop view if exists public.v_source_performance;
drop view if exists public.v_estimate_accuracy;
drop view if exists public.v_promise_vs_delivery;
drop view if exists public.v_weekly_capacity;
drop view if exists public.v_job_performance;
drop view if exists public.v_lost_analysis;
drop view if exists public.v_pipeline_open;
drop view if exists public.v_enquiry_cycle_times;
drop view if exists public.v_enquiry_funnel;
drop view if exists public.v_enquiry_flat;

drop table if exists public.dim_date;
